name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version of Node.js compatible with the action

      - name: Install Dependencies
        run: npm install yoshi389111/github-profile-3d-contrib@0.7.1

      - name: Generate GitHub Profile 3D Contribution
        run: |
          npx github-profile-3d-contrib
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generate GitHub Profile 3D Contribution"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
